### ISSUE TITLE
[v3.0.0] Missing cleanup of fluentd and fluentbit on upgrade provedure

### ISSUE THREAD

**Issue by g-iannelli** [sighupio/fury-kubernetes-logging#104]
On https://github.com/sighupio/fury-kubernetes-logging/releases/tag/v3.0.0 release description, under the upgrade guide, it's missing the reference to delete the `fluentd` StatefulSet and the `fluentbit` DaemonSet

**Comment by ralgozino** [comment]
Those 2 workloads are managed by the Logging Operator, it should not be needed any manual intervention.

Or am I missing something?

cc @nutellinoit

**Comment by nutellinoit** [comment]
There is no mention on removing fluentd and fluentbit because it's already mentioned on the v2.0.0 https://github.com/sighupio/fury-kubernetes-logging/releases/tag/v2.0.0

Also, in the fury-distribution upgrade guides https://github.com/sighupio/fury-distribution/tree/main/docs/upgrades the deletion of the fluentd and fluentbit sts and ds is mentioned.

From which Fury version where you upgrading to? You can fine the upgrade paths here https://github.com/sighupio/fury-distribution/blob/main/docs/upgrades/UPGRADE_PATH.md
